package net.start.model;
// Generated Feb 10, 2025, 12:35:46 PM by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Customer generated by hbm2java
 */

@Entity

@Table(name = "customer" )
public class Customer implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "CUS_ID")
	private Integer cusId;
	private String name;
	private String username;
	private String pwd;
	private String userroles;

	@JsonIgnore
	@OneToMany(targetEntity=Phonenumber.class)
	private Set phonenumbers = new HashSet(0);

	public Customer() {
	}

	public Customer(String username, String pwd) {
		this.username = username;
		this.pwd = pwd;
	}

	public Customer(String name, String username, String pwd, String userroles, Set phonenumbers) {
		this.name = name;
		this.username = username;
		this.pwd = pwd;
		this.userroles = userroles;
		this.phonenumbers = phonenumbers;
	}

	public Integer getCusId() {
		return this.cusId;
	}

	public void setCusId(Integer cusId) {
		this.cusId = cusId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getUserroles() {
		return this.userroles;
	}

	public void setUserroles(String userroles) {
		this.userroles = userroles;
	}

	public Set getPhonenumbers() {
		return this.phonenumbers;
	}

	public void setPhonenumbers(Set phonenumbers) {
		this.phonenumbers = phonenumbers;
	}

}
